# Generated by Django 5.2.4 on 2025-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
