# Generated by Django 5.2.4 on 2025-08-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_remove_contact_subject_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
