# Generated by Django 5.2.4 on 2025-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
